spring:
  datasource:
    # Production MySQL database
    url: jdbc:mysql://localhost:3306/product-service?useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    hikari: # Connection pool configuration (adjust for production needs)
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 30000
      pool-name: ProductServiceHikariCP
      max-lifetime: 2000000
      connection-timeout: 30000

server:
  port: 8081 # Consistent port across environments (discovery handles routing)

logging:
  level:
    com.example.product: INFO # Less verbose logging

